"""initial_schema

Revision ID: 07b0e45be844
Revises: 
Create Date: 2026-09-13 11:21:58.681038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b0e45be844'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_name'), 'appointments', ['doctor_name'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_patient_id'), 'lab_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_status'), 'lab_reports', ['status'], unique=False)
    op.create_index(op.f('ix_lab_reports_test_name'), 'lab_reports', ['test_name'], unique=False)
    op.add_column('medicines', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('medicines', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('medicines', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_medicines_category'), 'medicines', ['category'], unique=False)
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medicines_manufacturer'), 'medicines', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=True)
    op.create_index(op.f('ix_patients_registration_number'), 'patients', ['registration_number'], unique=True)
    op.alter_column('prescriptions', 'instructions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_patient_id'), 'queue_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_status'), 'queue_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_entries_status'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_patient_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.alter_column('prescriptions', 'instructions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_patients_registration_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.alter_column('patients', 'emergency_contact',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_manufacturer'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_category'), table_name='medicines')
    op.alter_column('medicines', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('medicines', 'updated_at')
    op.drop_column('medicines', 'created_at')
    op.drop_index(op.f('ix_lab_reports_test_name'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_status'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_patient_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_name'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    # ### end Alembic commands ###
